apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventprocessor
  namespace: {{ .Values.NAMESPACE }}
spec:
  selector:
    matchLabels:
      app: eventprocessor
      component: eventprocessor
  template:
    metadata:
      labels:
        app: eventprocessor
        component: eventprocessor
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ print .Values.APP_IDENTITY_NAME }}
      containers:
      - name: eventprocessor
        image: {{ print .Values.ACR_NAME ".azurecr.io/logicapp-demo:" .Values.COMMIT_VERSION }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: eventprocessorconfig
        resources:
          limits:
            cpu: "2"
            memory: 2048Mi
          requests:
            cpu: "1"
            memory: 1024Mi