apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ print .Values.APP_IDENTITY_NAME }}
  namespace: {{ .Values.NAMESPACE }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.ARM_WORKLOAD_APP_ID }}
    azure.workload.identity/tenant-id: {{ .Values.ARM_TENANT_ID }}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: SecretsAccess
  namespace: {{ .Values.NAMESPACE }}
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ print "SecretAccess-binding-" .Values.APP_IDENTITY_NAME  }}
  namespace: {{ .Values.NAMESPACE }}
subjects:
  - kind: ServiceAccount
    name: {{ print .Values.APP_IDENTITY_NAME }}
roleRef:
  kind: Role
  name: SecretsAccess
  apiGroup: rbac.authorization.k8s.io