apiVersion: v1
kind: ConfigMap
metadata:
  name: eventprocessorconfig
  namespace: {{ .Values.NAMESPACE }}
data:
  FUNCTIONS_WORKER_RUNTIME: node
  FUNCTIONS_EXTENSION_VERSION: ~4
  WORKFLOWS_MANAGEMENT_BASE_URI: "https://management.azure.com/"
  EVENTHUB_CONNECTION__credential: managedidentity            
  EVENTHUB_CONNECTION__clientId: {{ .Values.MSI_CLIENTID }}  
  EVENTHUB_CONNECTION__fullyQualifiedNamespace: {{ print .Values.EVENTHUB_NAMESPACE_NAME ".eventhub.windows.net" }}
  AzureWebJobsStorage: {{ print "DefaultEndpointsProtocol=https;AccountName=" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ";AccountKey=" .Values.WEBJOB_STORAGE_ACCOUNT_KEY ";EndpointSuffix=core.windows.net" }}
  #AzureWebJobsStorage__accountName: {{ .Values.WEBJOB_STORAGE_ACCOUNT_NAME }}
  WORKFLOWS_TENANT_ID: {{ .Values.WORKFLOWS_TENANT_ID }}
  WORKFLOWS_SUBSCRIPTION_ID: {{ .Values.WORKFLOWS_SUBSCRIPTION_ID }}
  WORKFLOWS_RESOURCE_GROUP_NAME: {{ .Values.WORKFLOWS_RESOURCE_GROUP_NAME }}
  WORKFLOWS_LOCATION_NAME: {{ .Values.WORKFLOWS_LOCATION_NAME }}
  AZUREFUNCTIONS_SQLBINDINGS_TELEMETRY_OPTOUT: "true"
  WEBSITE_HOSTNAME: "localhost"
  AzureWebJobsSecretStorageType: "files"
  FUNCTIONS_V2_COMPATIBILITY_MODE: "true"
  AZURE_FUNCTIONS_ENVIRONMENT: "Production" 
