apiVersion: v1
kind: ConfigMap
metadata:
  name: eventprocessorconfig
  namespace: {{ .Values.NAMESPACE }}
data:
  FUNCTIONS_WORKER_RUNTIME: node  
  WORKFLOWS_MANAGEMENT_BASE_URI: "https://management.azure.com/"              
  EVENTHUB_CONNECTION__clientId: {{ .Values.MSI_CLIENTID }}  
  EVENTHUB_CONNECTION__fullyQualifiedNamespace: {{ print .Values.EVENTHUB_NAMESPACE_NAME ".eventhub.windows.net" }}
  AzureWebJobsStorage__queueServiceUri: {{ print "https://" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ".queue.core.windows.net" }}
  AzureWebJobsStorage__tableServiceUri: {{ print "https://" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ".table.core.windows.net" }}
  AzureWebJobsStorage__blobServiceUri: {{ print "https://" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ".blob.core.windows.net" }}
  WORKFLOWS_TENANT_ID: {{ .Values.WORKFLOWS_TENANT_ID }}
  WORKFLOWS_SUBSCRIPTION_ID: {{ .Values.WORKFLOWS_SUBSCRIPTION_ID }}
  WORKFLOWS_RESOURCE_GROUP_NAME: {{ .Values.WORKFLOWS_RESOURCE_GROUP_NAME }}
  WORKFLOWS_LOCATION_NAME: {{ .Values.WORKFLOWS_LOCATION_NAME }}