apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventprocessor
  namespace: {{ .Values.NAMESPACE }}
spec:
  selector:
    matchLabels:
      app: eventprocessor
  template:
    metadata:
      labels:
        app: eventprocessor
        aadpodidbinding: {{ .Values.MSI_SELECTOR  }} 
    spec:
      containers:
      - name: eventprocessor
        image: {{ print .Values.ACR_NAME "/la-eventprocessor:" .Values.COMMIT_VERSION }}
        imagePullPolicy: Always
        env:
        - name: EVENTHUB_CONNECTION__credential
          value: managedidentity
        envFrom:
        - configMapRef:
            name: eventprocessorconfig
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: "2"
            memory: 2048Mi
          requests:
            cpu: "1"
            memory: 1024Mi