
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: azure-logicapps-test
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: bjd145.azurecr.io/logicapps-simple:0.1
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: azure-logicapps-runtime-secrets
        env:
          - name: FUNCTIONS_WORKER_RUNTIME
            value: "dotnet"
          - name: AzureWebJobsSecretStorageType
            value: files   
        volumeMounts:
          - name: secrets
            mountPath: "/azure-logicapps-host/Secrets"
      volumes:
      - name: secrets
        secret:
          secretName: azure-logicapps-secrets